config:
  host: devx-helloworld-springboot-07brp.nonp-dev-4.use1.eng-nonprod.flexport.internal
  namespace: devx-helloworld-springboot-07brp
  image:
    name: artifactory.flexport.io/devx-helloworld-springboot-07brp-docker-dev-local/devx-helloworld-springboot-07brp
    tag: 0.0.1-SNAPSHOT
